inputs :
  - potato.rsl
  - potato.trlc

trlc_config: |
  example.Codebeamer_Id {
    to_string = "$(item)@$(version)"
    to_string = "$(item)"
  }
  
  example.Requirement {
    description = text
    just_up     = just_up
    just_down   = just_down
  }
  
  example.Tagged_Requirement {
    description = extra_text
    tags "req"  = trace_cb
  }
  
  example.Linked_Requirement {
    tags "req" = trace_trlc
  }
